name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"   # Run every Monday at 08:00

jobs:
  test:
    strategy:
      # Default value means that a failure in one OS cancels all 
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11 ]
        os: [ windows-latest ] # macos-latest, ubuntu-latest
        ston: [ .ci.ston ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Download DLLs
        uses: schmiddim/action-wget-unzip@v2
        with:
          url: 'https://github.com/harfbuzz/harfbuzz/releases/download/5.2.0/harfbuzz-win64-5.2.0.zip'
          destination: '/home/runner/.smalltalkCI/_builds/'
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} ${{ matrix.ston }}
        shell: bash
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
